services:
  postgres:
    image: postgres:17

    container_name: dagify-postgres

    restart: unless-stopped

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: dagify
      POSTGRES_PASSWORD: dagify
      POSTGRES_DB: dagify

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: